name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - "*"
    paths:
      - "**"
      - "!**.md"
    tags-ignore:
      - "*"
  pull_request:
    paths:
      - "**"
      - "!**.md"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [8.0.403]
        pnpm: [10.13.1]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm }}
      - name: Run test
        run: dotnet run test
